### ISSUE TITLE
Update framework to more recent version

### ISSUE THREAD

**Issue by lastlink** [snohio/odevs#27]
# Update 11ty framework

## User Story

Pull in new features, security fixes, easier to follow documentation if framework is up to date. Also may get playright tests working with new update that would allow template testing

## Tasks

- [ ] Pull a new starter
- [ ] Copy over changes
- [ ] Test current code works

## Extra Notes

* see https://github.com/dustin-jw/eleventy-starter/tree/main
* current versions
   * "@11ty/eleventy": "^2.0.1"
   * node: v16.13.2
   * browser-sync
   * jest
* in starter
   * "@11ty/eleventy": "^2.0.1"
   * node: >=20
   * vitest and playright
   * scss compiler
